"""Star

Revision ID: 01e7baa6ce2d
Revises: 9985f7077d63
Create Date: 2025-01-16 19:57:38.567210

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '01e7baa6ce2d'
down_revision: Union[str, None] = '9985f7077d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stars',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('status', postgresql.ENUM('ON_MARKET', 'BUY', 'SELLER_ACCEPT',
                                                        'GIFT_TRANSFERRED', 'GIFT_RECEIVED', name='orderstatus', create_type=False), nullable=False),
                    sa.Column('created_order_date', sa.TIMESTAMP(), nullable=True),
                    sa.Column('completed_order_date', sa.TIMESTAMP(), nullable=True),
                    sa.Column('seller_id', sa.BigInteger(), nullable=False),
                    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_constraint('_type_number_uc', 'orders', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_type_number_uc', 'orders', ['type', 'number'])
    op.drop_column('orders', 'is_vip')
    op.drop_table('stars')
    # ### end Alembic commands ###
