"""PackId

Revision ID: 1ae6122e6c9d
Revises: c082d31331a0
Create Date: 2025-01-21 23:17:04.535783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae6122e6c9d'
down_revision: Union[str, None] = 'c082d31331a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('pack_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'pack_id')
    # ### end Alembic commands ###
