"""Initial

Revision ID: 2b63ed36d438
Revises: 
Create Date: 2025-01-05 16:39:01.167326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b63ed36d438'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lts',
    sa.Column('last_lt', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('last_lt')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('deposit_comment', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deposit_comment')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('type', postgresql.ENUM('DUROV_CAP', 'SIGNET_RING', 'PLUSH_PEPE', 'PERFUME_BOTTLE', 'SPY_AGARIC', 'SHARP_TONGUE', 'SCARED_CAT', 'HEX_POT', 'KISSED_FROG', 'SANTA_HAT', 'HOMEMADE_CAKE', 'SKULL_FLOWER', 'PRECIOUS_PEACH', 'SPICED_WINE', 'JELLY_BUNNY', 'ETERNAL_ROSE', 'BERRY_BOX', 'VINTAGE_CIGAR', 'MAGIC_POTION', 'EVIL_EYE', name='gifttype'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('model', sa.Float(), nullable=False),
    sa.Column('pattern', sa.Float(), nullable=False),
    sa.Column('background', sa.Float(), nullable=False),
    sa.Column('rarity', postgresql.ENUM('COMMON', 'RARE', 'MYTHICAL', 'LEGEND', name='giftrarity'), nullable=False),
    sa.Column('status', postgresql.ENUM('ON_MARKET', 'BUY', 'GIFT_TRANSFERRED', 'GIFT_RECEIVED', name='orderstatus'), nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_referrals',
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('referral_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('referral_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_referrals')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('lts')
    # ### end Alembic commands ###
