"""UC

Revision ID: 2fa89ab85fe2
Revises: 9985f7077d63
Create Date: 2025-01-12 03:19:39.403270

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2fa89ab85fe2'
down_revision: Union[str, None] = '9985f7077d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_type_number_uc', 'orders', ['type', 'number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_type_number_uc', 'orders', type_='unique')
    # ### end Alembic commands ###
