"""Model name

Revision ID: 4d7aedb68f03
Revises: 6003c84eb387
Create Date: 2025-03-25 11:51:44.544183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7aedb68f03'
down_revision: Union[str, None] = '6003c84eb387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historys', sa.Column('model_name', sa.String(), nullable=True))
    op.drop_column('historys', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historys', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('historys', 'model_name')
    # ### end Alembic commands ###
