"""History

Revision ID: 6003c84eb387
Revises: 3a98eb5aef6e
Create Date: 2025-03-25 00:15:29.870124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6003c84eb387'
down_revision: Union[str, None] = '3a98eb5aef6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', postgresql.ENUM('BUY_GIFT', 'SELL_GIFT', 'DEPOSIT', 'WITHDRAW', 'BUY_STARS', 'SELL_STARS', name='historytype'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('gift', postgresql.ENUM('DUROV_CAP', 'SIGNET_RING', 'PLUSH_PEPE', 'PERFUME_BOTTLE', 'SPY_AGARIC', 'SHARP_TONGUE', 'SCARED_CAT', 'HEX_POT', 'KISSED_FROG', 'SANTA_HAT', 'HOMEMADE_CAKE', 'SKULL_FLOWER', 'PRECIOUS_PEACH', 'SPICED_WINE', 'JELLY_BUNNY', 'ETERNAL_ROSE', 'BERRY_BOX', 'VINTAGE_CIGAR', 'MAGIC_POTION', 'EVIL_EYE', 'TRAPPED_HEART', 'LUNAR_SNAKE', 'PARTY_SPARKLER', 'JESTER_HAT', 'GENIE_LAMP', 'WITCH_HAT', 'COOKIE_HEART', 'ETERNAL_CANDLE', 'HANGING_STAR', 'JINGLE_BELLS', 'CRYSTAL_BALL', 'SWISS_WATCH', 'DESK_CALENDAR', 'FLYING_BROOM', 'HYPNO_LOLLIPOP', 'LOVE_CANDLE', 'SNOW_MITTENS', name='gifttype', create_type=False), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historys')
    # ### end Alembic commands ###
