"""Giveaways

Revision ID: 7133aa8d4918
Revises: 25d0194ca46c
Create Date: 2025-04-05 21:52:52.892176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7133aa8d4918'
down_revision: Union[str, None] = '25d0194ca46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giveaways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('SUBSCRIPTION', 'SUBSCRIPTION_PAID_PARTICIPANT', 'SUBSCRIPTION_PAID_TICKET', name='giveawaytype'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('gifts_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channels_usernames', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quantity_members', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('giveaways')
    # ### end Alembic commands ###
