"""Initial

Revision ID: 85bfe8ccf049
Revises: 
Create Date: 2025-03-19 03:39:43.609980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85bfe8ccf049'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lts',
    sa.Column('last_lt', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('last_lt')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('deposit_comment', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deposit_comment')
    )
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pack_id', sa.String(), nullable=False),
    sa.Column('last_bid', sa.Float(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('DUROV_CAP', 'SIGNET_RING', 'PLUSH_PEPE', 'PERFUME_BOTTLE', 'SPY_AGARIC', 'SHARP_TONGUE', 'SCARED_CAT', 'HEX_POT', 'KISSED_FROG', 'SANTA_HAT', 'HOMEMADE_CAKE', 'SKULL_FLOWER', 'PRECIOUS_PEACH', 'SPICED_WINE', 'JELLY_BUNNY', 'ETERNAL_ROSE', 'BERRY_BOX', 'VINTAGE_CIGAR', 'MAGIC_POTION', 'EVIL_EYE', 'TRAPPED_HEART', 'LUNAR_SNAKE', 'PARTY_SPARKLER', 'JESTER_HAT', 'GENIE_LAMP', 'WITCH_HAT', 'COOKIE_HEART', 'ETERNAL_CANDLE', 'HANGING_STAR', 'JINGLE_BELLS', 'CRYSTAL_BALL', 'SWISS_WATCH', 'DESK_CALENDAR', 'FLYING_BROOM', 'HYPNO_LOLLIPOP', 'LOVE_CANDLE', 'SNOW_MITTENS', name='gifttype'), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('model', sa.Float(), nullable=False),
    sa.Column('pattern', sa.Float(), nullable=False),
    sa.Column('background', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('pattern_name', sa.String(), nullable=False),
    sa.Column('background_name', sa.String(), nullable=False),
    sa.Column('rarity', postgresql.ENUM('COMMON', 'RARE', 'MYTHICAL', 'LEGEND', name='giftrarity'), nullable=False),
    sa.Column('completed_order_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_vip', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', postgresql.ENUM('ON_MARKET', 'BUY', 'SELLER_ACCEPT', 'GIFT_TRANSFERRED', 'GIFT_RECEIVED', name='orderstatus'), nullable=False),
    sa.Column('created_order_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_order_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_referrals',
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('referral_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('referral_id')
    )
    op.create_table('withdraw_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('wallet', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdraw_requests')
    op.drop_table('user_referrals')
    op.drop_table('stars')
    op.drop_table('orders')
    op.drop_table('auctions')
    op.drop_table('users')
    op.drop_table('lts')
    # ### end Alembic commands ###
