"""Add is active

Revision ID: 9985f7077d63
Revises: 2921c993aaad
Create Date: 2025-01-11 14:00:46.129422

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9985f7077d63'
down_revision: Union[str, None] = '2921c993aaad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('orders', sa.Column('is_vip', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_active')
    op.drop_column('orders', 'is_vip')
    # ### end Alembic commands ###
