"""Giveaway

Revision ID: a86379e83c95
Revises: 0d27e4d4cd2a
Create Date: 2025-04-06 01:36:17.237680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a86379e83c95'
down_revision: Union[str, None] = '0d27e4d4cd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giveaways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('SUBSCRIPTION', 'SUBSCRIPTION_PAID_PARTICIPANT', 'SUBSCRIPTION_PAID_TICKET', name='giveawaytype'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('gifts_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('participants_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channels_usernames', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quantity_members', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('giveaways')
    # ### end Alembic commands ###
