"""Order

Revision ID: b531883c9108
Revises: d5001e81f34a
Create Date: 2025-01-04 21:34:56.658589

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b531883c9108'
down_revision: Union[str, None] = 'd5001e81f34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('image_url', sa.String(), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('seller_id', sa.BigInteger(), nullable=False),
                    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
                    sa.Column('status', postgresql.ENUM('ON_MARKET', 'BUY', 'GIFT_TRANSFERRED',
                                                        'GIFT_RECEIVED', name='orderstatus'), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_banned')
    op.drop_table('orders')
    # ### end Alembic commands ###
