"""Lt

Revision ID: d5001e81f34a
Revises: 51e5b8d69b98
Create Date: 2025-01-04 14:14:59.204398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5001e81f34a'
down_revision: Union[str, None] = '51e5b8d69b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lts',
    sa.Column('last_lt', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('last_lt')
    )
    op.add_column('users', sa.Column('deposit_comment', sa.String(), nullable=False))
    op.add_column('users', sa.Column('balance', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'users', ['deposit_comment'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'balance')
    op.drop_column('users', 'deposit_comment')
    op.drop_table('lts')
    # ### end Alembic commands ###
