"""Auction

Revision ID: ef11c8524c37
Revises: 85bfe8ccf049
Create Date: 2025-03-22 02:36:40.784529

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ef11c8524c37'
down_revision: Union[str, None] = '85bfe8ccf049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auctions')
    op.add_column('orders', sa.Column('min_step', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('auction_end_time', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'auction_end_time')
    op.drop_column('orders', 'min_step')
    op.create_table('auctions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pack_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_bid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name='auctions_buyer_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='auctions_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='auctions_pkey')
    )
    # ### end Alembic commands ###
