name: Deploy App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server & restart app
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/nest/GiftsMarket
            git pull
            screen -S back -X stuff $'\003'
            screen -S back -X stuff $'uvicorn --factory src.entrypoint.main:get_fastapi_app\n'
